### ISSUE TITLE
Unable to initialise a deno project

### ISSUE THREAD

**Issue by Tochemey** [zhmushan/deno_init#1]
Hello
I am a newbie with deno.  When I try to initialize a deno project I got the following error:
`Compiling https://denolib.com/zhmushan/deno_init/mod.ts
Downloading https://denolib.com/zhmushan/deno_init/deno
Uncaught Other: Import 'https://denolib.com/zhmushan/deno_init/deno' failed: 404 Not Found
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:86:5)
    at fetchModuleMetaData (js/os.ts:73:19)
    at _resolveModule (js/compiler.ts:255:38)
    at resolveModuleNames (js/compiler.ts:486:35)
    at compilerHost.resolveModuleNames (third_party/node_modules/typescript/lib/typescript.js:121106:138)
    at resolveModuleNamesWorker (third_party/node_modules/typescript/lib/typescript.js:88311:127)
    at resolveModuleNamesReusingOldState (third_party/node_modules/typescript/lib/typescript.js:88553:24)`

**Comment by zhmushan** [comment]
`deno_init` is just a temporary solution when no vscode extension available. Now you can use [vscode-deno](https://github.com/justjavac/vscode-deno)
